### Register User
POST https://3depox.cz/api/auth/register
Content-Type: application/json

{
  "Username": "testus1er123411",
  "Password": "pas1sword12311",
  "Email": "kaj.pelc1a1k@seznam.cz1",
  "PhoneNumber": "123416789",
  "StreetAndNumber": "1213456789",
  "City": "1234561789",
  "PostalCode": "1234516789"
}


###
POST https://3depox.cz/api/auth/login
Content-Type: application/json

{
  "Email":"kaj.pelcak@seznam.cz1",
  "Password":"password12311"
}
###

GET https://3depox.cz/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6InRlc3R1c2VyMTIzNDExIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzE4NzkwMTE3LCJleHAiOjE3MTg3OTM3MTd9.hPHWO8pb8e4veE5nN2gJtpTfoWBh3W1-uqgKCXg8ASk