### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "Username": "PetrPelcak",
  "Password": "Pepe1409",
  "Email": "petrpelcak@seznam.cz",
  "PhoneNumber": "123456789",
  "StreetAndNumber": "1213456789",
  "City": "1234561789",
  "PostalCode": "1234516789"
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "Email":"kaj.pelc1a21k@seznam.cz1",
  "Password":"pas1sword12311"
}
###

GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6InRlc3R1czFlMnIxMjM0MTEiLCJyb2xlIjoiVXNlciIsImlhdCI6MTcxODc5Mjc4MywiZXhwIjoxNzE4Nzk2MzgzfQ.qeyDJN3sntPLJTEbh0LrBuz-jAQ8RGx0I_FFpqo9Tt4