### Register User
POST https://3depox.cz/api/auth/register
Content-Type: application/json

{
  "Username": "testuser12341",
  "Password": "password1231",
  "Email": "gryvdycz@gmail.com1",
  "PhoneNumber": "123456789",
  "StreetAndNumber": "123456789",
  "City": "123456789",
  "PostalCode": "123456789"
}


###
POST https://3depox.cz/api/auth/login
Content-Type: application/json

{
  "Email":"kaja.pelcak@seznam.cz",
  "Password":"Kaja172004"
}
###

GET https://3depox.cz/api/auth/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTg3MzI5NDAsImV4cCI6MTcxODczNjU0MH0.oy3L3tC1SdA2DolBcosDrPkzhGpa8QoCdCzC0pbZlRE

###
DELETE    http://localhost:5173/api/admin/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6IkthcmVsIFBlbMSNw6FrIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzE5OTI2NTk0LCJleHAiOjE3MTk5NTUzOTR9.EQVBYC_NIv5Y_yqto78nOBpGI7ktHsJcpCMk_j5Mfd8
Content-Type: application/json

{
  "CategoryName": "Auta",
  "CategoryId": 11
}

###
GET http://localhost:5173/api/admin/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6IkthcmVsIFBlbMSNw6FrIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzE5OTI2NTk0LCJleHAiOjE3MTk5NTUzOTR9.EQVBYC_NIv5Y_yqto78nOBpGI7ktHsJcpCMk_j5Mfd8
###
POST http://localhost:5173/api/admin/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6IkthcmVsIFBlbMSNw6FrIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzE5OTI2NTk0LCJleHAiOjE3MTk5NTUzOTR9.EQVBYC_NIv5Y_yqto78nOBpGI7ktHsJcpCMk_j5Mfd8
Content-Type: application/json

{
  "CategoryName": "Auta"
}