### Register User
POST http://localhost:5173/api/auth/register
Content-Type: application/json

{
  "Username": "testuser1234",
  "Password": "password123",
  "Email": "gryvdycz@gmail.com",
  "PhoneNumber": "123456789",
  "StreetAndNumber": "123456789",
  "City": "123456789",
  "PostalCode": "123456789"
}


